Gzip test file compare

diff --git a/examples/gzip-1.3.12/Makefile b/examples/gzip-1.3.12/Makefile
--- a/examples/gzip-1.3.12/Makefile
+++ b/examples/gzip-1.3.12/Makefile
@@ -24,20 +24,31 @@ compress: ${OUT_DIR}
 
 
 test_compress: 
+	@echo "\t\tTest Compress"
+	@echo "File Existence Check:"
 	@# Testing if compressed file produced
 	@cp huffman.c ${OUT_DIR}/work_dir && \
 	cd ${OUT_DIR}/work_dir && \
 	./gzip_fin_stripped && \
-	test -f huffman.c.gz && echo "gzip test compress passed!" || echo "gzip test compress failed!" 
-
+	test -f huffman.c.gz && echo "\tgzip test compress file exist? Passed!" || echo "gzip test compress file exist? Failed!" 
+	@echo "Comparing File Sizes:"
 	@# Printing File sizes
-	@echo -n "Source File Size:\t"
+	@echo -n "\tSource File Size:\t"
 	@stat -L -c %s huffman.c
-	@echo -n "Compressed File Size:\t"
+	@echo -n "\tCompressed File Size:\t"
 	@stat -L -c %s ${OUT_DIR}/work_dir/huffman.c.gz
+	@echo "Output comparison to Baseline:"
+	@cmp -i 10 ./huffman.c.gz ${OUT_DIR}/work_dir/huffman.c.gz; \
+	RETVAL=$$?; \
+	if [ $$RETVAL -eq 0 ]; then \
+		echo "\tgzip test baseline compare? Passed!"; \
+	else \
+		echo "\tgzip test baseline compare? Failed!"; \
+	fi
 
+	
 
-
+	
 .PHONY: ${GZIP_BITCODE}
 ${GZIP_BITCODE}: ${GZIP_NAME}
 	cp ${GZIP_PATCH} ${GZIP_NAME} && \
@@ -46,7 +57,8 @@ ${GZIP_BITCODE}: ${GZIP_NAME}
 	CC=${BITCODE_WRAPPER} CFLAGS="-DHAVE_CONFIG_H -DVERSION="\"1.17\"" -Xclang -disable-O0-optnone" ./configure && \
 	CC=${BITCODE_WRAPPER} make && \
 	${BITCODE_EXTRACT} ${GZIP} && \
-	mv ${GZIP_BITCODE} ../
+	mv ${GZIP_BITCODE} ../  && \
+	${GZIP} --keep --force --quiet ../huffman.c 
 		
 ${OUT_DIR}:
 	mkdir -p ${OUT_DIR}
